### ISSUE TITLE
goooogle的hosts失效了哦~

### ISSUE THREAD

**Issue by AlliotTech** [szhielelp/OmegaHosts#1]
hosts最近死的差不多了。。。SS又要到期了~ 蛋疼

**Comment by szhielelp** [comment]
哈哈我看到fork了, 确实已经失效了, 我前段时间用免费一年的AWS搭建了SS, 你可以试试

**Comment by AlliotTech** [comment]
哇哦~ 有地址码~

**Comment by szhielelp** [comment]
啊哈那可是私人使用的SS, 没办法公开, 有时间你搭建个试试真的很简单 _(:з」∠)_

**Comment by AlliotTech** [comment]
我是说的。。。 AWS那个免费一年的地址。。

**Comment by szhielelp** [comment]
捂脸+尴尬.jpg
直接aws中国主页搜ec2服务就是_(•̀ω•́ 」∠)_
